# This is a basic workflow to help you get started with Actions

name: CI Service Versions and Regions
on:
  schedule:
    # Runs "everyday at 00 hours"
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9' 
          architecture: 'x64'
          cache: 'pip'
      - run: pip install -r requirements.txt
        env: 
          NOTIFICATION_URL: ${{ secrets.NOTIFICATION_URL }}
      - run: python regions/extract.py
      - run: python main.py

      # Git push raw json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Update Versions and Regions.
